M06 Exercises Day 2

Rachel Grace, Davi Meran

Exercise 1

In [31]:
import numpy as np
import random
def rollDie(n, m = 6, sort = False):
    lst = [random.randint(0, m) for x in range(n)]
    if sort == False:
        return lst.sort(reverse = False)
    else:
        return lst.sort(reverse = True)
    return lst
rollDie(8,6,True)

In [30]:
output = rollDie(8)
print(output)

None


Exercise 3

In [34]:
a = np.array([[1, 2, 3], [3, 4, 5], [5, 6, 7]])
np.linalg.det(a)

1.6875389974302314e-15

In [36]:
b = np.array([[1,0,0],[0,1,0],[0,0,1]])
np.linalg.det(b)

1.0

In [38]:
c = np.array([[1, 2], [1, 2]])
np.linalg.det(c)

0.0

Exercise 4

In [43]:
np.linalg.eig(a)

(array([ 1.29282032e+01, -9.28203230e-01,  7.58225307e-16]),
 array([[-0.28932501, -0.80222426,  0.40824829],
        [-0.53988782, -0.10747767, -0.81649658],
        [-0.79045062,  0.58726892,  0.40824829]]))

In [40]:
np.linalg.eigvals(a)

array([ 1.29282032e+01, -9.28203230e-01,  7.58225307e-16])

In [44]:
np.linalg.eig(b)

(array([1., 1., 1.]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

In [42]:
np.linalg.eigvals(b)

array([1., 1., 1.])

Exercise 5

In [47]:
p = [[1, 2], [3, 4]]
q = [[5, 6], [7, 8]]
np.dot(p, q)

array([[19, 22],
       [43, 50]])

Exercise

In [52]:
arr = [[0,1,2,3,4,5],[6,7,8,9,10,11]]
#dif0 = np.amax(arr[0]) - np.amin(arr[0])
#dif1 = np.amax(arr[1]) - np.amin(arr[1])
#arrlist = [dif0, dif1]
arrlist = [np.amax(arr[i]) - np.amin(arr[i]) for i in range(len(arr))]
print(arrlist)

[5, 5]


Exercise

In [54]:
new_matrix = [[1, 2], [3, 4]]
np.linalg.norm(new_matrix)

5.477225575051661

Exercise

In [56]:
np.linalg.qr(new_matrix)

(array([[-0.31622777, -0.9486833 ],
        [-0.9486833 ,  0.31622777]]),
 array([[-3.16227766, -4.42718872],
        [ 0.        , -0.63245553]]))